version: '3.8'

services:
  # Redis for throttling and shared state
  redis:
    image: redis:7-alpine
    container_name: kumo-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 2gb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Main KumoMTA daemon (following official pattern)
  kumod:
    image: ghcr.io/kumocorp/kumomta:main
    container_name: kumod-enterprise
    hostname: kumod
    volumes:
      - ./policy:/opt/kumomta/etc/policy:ro

      - kumo_data_spool:/var/spool/kumomta/data
      - kumo_meta_spool:/var/spool/kumomta/meta
      - kumo_logs:/var/log/kumomta
    ports:
      - "0.0.0.0:25:25"
      - "0.0.0.0:587:587"
      - "0.0.0.0:8000:8000"
    depends_on:
      redis:
        condition: service_healthy
      tsa:
        condition: service_healthy
    restart: unless-stopped
    
  # TSA daemon for traffic shaping automation (official pattern)
  tsa:
    image: ghcr.io/kumocorp/kumomta:main
    container_name: kumo-tsa
    hostname: tsa
    command: runuser -u kumod -- /opt/kumomta/sbin/tsa-daemon --policy /opt/kumomta/etc/policy/tsa_init.lua
    volumes:
      - ./policy:/opt/kumomta/etc/policy:ro
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["/opt/kumomta/sbin/validate-shaping", "/opt/kumomta/etc/policy/shaping.toml"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KUMO_POLICY=/opt/kumomta/etc/policy/init.lua
      - KUMO_LOG_LEVEL=info
      - KUMO_PERFORMANCE_MODE=high
      - KUMO_API_BIND=0.0.0.0:8000
      - KUMO_ALLOWED_IPS=151.236.251.75,149.28.244.166
    command: ["/bin/sh", "-lc", "install -d -o kumod -g kumod -m 750 /var/spool/kumomta/data /var/spool/kumomta/meta /var/log/kumomta && exec /opt/kumomta/sbin/kumod --policy /opt/kumomta/etc/policy/init.lua --user kumod"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: kumo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://89.117.75.190:9090'
    restart: unless-stopped
    depends_on:
      - kumod

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: kumo-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=kumomta123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://89.117.75.190:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    restart: unless-stopped
    depends_on:
      - prometheus

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: kumo-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped

  # Redis Exporter for Redis metrics
  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: kumo-redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    restart: unless-stopped
    depends_on:
      - redis

  # Blackbox Exporter for external monitoring
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: kumo-blackbox-exporter
    ports:
      - "9115:9115"
    volumes:
      - ./monitoring/blackbox.yml:/config/blackbox.yml:ro
    command:
      - '--config.file=/config/blackbox.yml'
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
  kumo_data_spool:
    driver: local
  kumo_meta_spool:
    driver: local
  kumo_logs:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  default:
    name: kumo-network
    driver: bridge