# Traffic Shaping Configuration for KumoMTA
# This file configures rate limiting and traffic shaping rules

[global]
# Global rate limits
max_connections_per_second = 100
max_messages_per_second = 1000

[domains]
# Domain-specific rate limits
[domains."gmail.com"]
max_connections_per_second = 10
max_messages_per_second = 100
max_concurrent_connections = 5

[domains."outlook.com"]
max_connections_per_second = 10
max_messages_per_second = 100
max_concurrent_connections = 5

[domains."yahoo.com"]
max_connections_per_second = 8
max_messages_per_second = 80
max_concurrent_connections = 4

# Default domain settings
[domains."*"]
max_connections_per_second = 5
max_messages_per_second = 50
max_concurrent_connections = 3