# KumoMTA Traffic Shaping Configuration
# Production-ready shaping rules for email delivery

# Gmail - Conservative limits to avoid throttling
[domain."gmail.com"]
max_connection_rate = "10/min"
max_deliveries_per_connection = 100
max_message_rate = "100/min"
connection_limit = 10
idle_timeout = "300s"

# Microsoft (Outlook, Hotmail, Live)
[domain."outlook.com"]
max_connection_rate = "10/min"
max_deliveries_per_connection = 100
max_message_rate = "100/min"
connection_limit = 10

[domain."hotmail.com"]
max_connection_rate = "10/min"
max_deliveries_per_connection = 100
max_message_rate = "100/min"
connection_limit = 10

# Yahoo - More restrictive
[domain."yahoo.com"]
max_connection_rate = "5/min"
max_deliveries_per_connection = 50
max_message_rate = "50/min"
connection_limit = 5

# Apple iCloud
[domain."icloud.com"]
max_connection_rate = "5/min"
max_deliveries_per_connection = 50
max_message_rate = "50/min"
connection_limit = 5

# Default rules for all other domains
[domain."*"]
max_connection_rate = "20/min"
max_deliveries_per_connection = 200
max_message_rate = "200/min"
connection_limit = 10
idle_timeout = "300s"
connect_timeout = "30s"