groups:
  - name: email_delivery_alerts
    rules:
      # High bounce rate alert
      - alert: HighBounceRate
        expr: rate(kumomta_messages_total{type="bounced"}[5m]) / rate(kumomta_messages_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: email_delivery
        annotations:
          summary: "High bounce rate detected"
          description: "Bounce rate is {{ $value | humanizePercentage }} (threshold: 5%) - IP reputation at risk!"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # Warning bounce rate
      - alert: WarningBounceRate
        expr: rate(kumomta_messages_total{type="bounced"}[5m]) / rate(kumomta_messages_total[5m]) > 0.03
        for: 5m
        labels:
          severity: warning
          service: email_delivery
        annotations:
          summary: "Bounce rate approaching threshold"
          description: "Bounce rate is {{ $value | humanizePercentage }} (threshold: 3%) - monitor closely"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # Low delivery rate
      - alert: LowDeliveryRate
        expr: rate(kumomta_messages_total{type="delivered"}[5m]) / rate(kumomta_messages_total[5m]) < 0.95
        for: 3m
        labels:
          severity: warning
          service: email_delivery
        annotations:
          summary: "Low email delivery rate"
          description: "Delivery rate is {{ $value | humanizePercentage }} (threshold: 95%)"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # Queue overflow
      - alert: QueueOverflow
        expr: kumomta_queue_depth > 1000
        for: 5m
        labels:
          severity: warning
          service: email_delivery
        annotations:
          summary: "Email queue is overflowing"
          description: "Queue depth is {{ $value }} emails - system may be overloaded"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # Critical queue overflow
      - alert: CriticalQueueOverflow
        expr: kumomta_queue_depth > 5000
        for: 2m
        labels:
          severity: critical
          service: email_delivery
        annotations:
          summary: "CRITICAL: Email queue severely backed up"
          description: "Queue depth is {{ $value }} emails - immediate attention required!"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

  - name: system_health_alerts
    rules:
      # KumoMTA service down
      - alert: KumoMTADown
        expr: up{job="kumod"} == 0
        for: 1m
        labels:
          severity: critical
          service: kumomta
        annotations:
          summary: "KumoMTA service is down"
          description: "KumoMTA instance {{ $labels.instance }} has been down for more than 1 minute"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # Redis down
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis service is down"
          description: "Redis instance {{ $labels.instance }} has been down for more than 1 minute"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # Prometheus down
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 1m
        labels:
          severity: critical
          service: monitoring
        annotations:
          summary: "Prometheus is down"
          description: "Prometheus instance {{ $labels.instance }} has been down for more than 1 minute"

  - name: performance_alerts
    rules:
      # High memory usage
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value | humanizePercentage }} (threshold: 90%)"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}% (threshold: 80%)"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Disk space is low"
          description: "Disk usage is {{ $value | humanizePercentage }} (threshold: 90%)"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

  - name: network_alerts
    rules:
      # SMTP port down
      - alert: SMTPPortDown
        expr: up{job="blackbox-smtp"} == 0
        for: 2m
        labels:
          severity: critical
          service: smtp
        annotations:
          summary: "SMTP port is down"
          description: "SMTP port {{ $labels.instance }} is not responding"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"

      # HTTP API down
      - alert: HTTPAPIDown
        expr: up{job="blackbox-http"} == 0
        for: 2m
        labels:
          severity: critical
          service: http
        annotations:
          summary: "HTTP API is down"
          description: "HTTP API endpoint {{ $labels.instance }} is not responding"
          dashboard: "http://localhost:3000/d/kumomta/kumomta-overview"
